#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("healthJourney.droid.Resource", IsApplication=true)]

namespace healthJourney.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::healthJourney.droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::healthJourney.droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::healthJourney.droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::healthJourney.droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::healthJourney.droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::healthJourney.droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::healthJourney.droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::healthJourney.droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::healthJourney.droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::healthJourney.droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::healthJourney.droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::healthJourney.droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::healthJourney.droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::healthJourney.droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::healthJourney.droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bell = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int columns4 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int comm_sharing_pic = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int diet = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exercise = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exercise1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int lifestyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int professional_advice = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int profilePic = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int profilePic2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int profilePic3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int profilePic4 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sleep = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int splashScreen = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sunrise = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040025
			public const int ViewSliderSection = 2130968613;
			
			// aapt resource value: 0x7f040027
			public const int adviceBtn = 2130968615;
			
			// aapt resource value: 0x7f040003
			public const int bkBtn = 2130968579;
			
			// aapt resource value: 0x7f040018
			public const int btmTabLayout = 2130968600;
			
			// aapt resource value: 0x7f040033
			public const int btmUsrInfoLayout = 2130968627;
			
			// aapt resource value: 0x7f040044
			public const int btmUsrInfoLayout2 = 2130968644;
			
			// aapt resource value: 0x7f040034
			public const int btm_usrNameTxt = 2130968628;
			
			// aapt resource value: 0x7f040045
			public const int btm_usrNameTxt2 = 2130968645;
			
			// aapt resource value: 0x7f040035
			public const int btm_usrPostTxt = 2130968629;
			
			// aapt resource value: 0x7f040046
			public const int btm_usrPostTxt2 = 2130968646;
			
			// aapt resource value: 0x7f04001c
			public const int cancelBtn = 2130968604;
			
			// aapt resource value: 0x7f04004f
			public const int columnNames = 2130968655;
			
			// aapt resource value: 0x7f040038
			public const int commentUsrIdTxt = 2130968632;
			
			// aapt resource value: 0x7f04003b
			public const int commentUsrIdTxt2 = 2130968635;
			
			// aapt resource value: 0x7f040049
			public const int commentUsrIdTxt2_2 = 2130968649;
			
			// aapt resource value: 0x7f04001b
			public const int community = 2130968603;
			
			// aapt resource value: 0x7f04001f
			public const int descText = 2130968607;
			
			// aapt resource value: 0x7f04004d
			public const int editText = 2130968653;
			
			// aapt resource value: 0x7f040050
			public const int exercise = 2130968656;
			
			// aapt resource value: 0x7f040008
			public const int forumLayout = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int headerTxt1 = 2130968589;
			
			// aapt resource value: 0x7f040012
			public const int headerTxt2 = 2130968594;
			
			// aapt resource value: 0x7f040017
			public const int headerTxt3 = 2130968599;
			
			// aapt resource value: 0x7f040029
			public const int healthJourney = 2130968617;
			
			// aapt resource value: 0x7f040023
			public const int imageView1 = 2130968611;
			
			// aapt resource value: 0x7f040052
			public const int imageView2 = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int imageView3 = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int imageView4 = 2130968660;
			
			// aapt resource value: 0x7f040051
			public const int linearLayout1 = 2130968657;
			
			// aapt resource value: 0x7f040028
			public const int linearLayout2 = 2130968616;
			
			// aapt resource value: 0x7f04001a
			public const int newPostBtn = 2130968602;
			
			// aapt resource value: 0x7f04004b
			public const int newThoughtsBtn = 2130968651;
			
			// aapt resource value: 0x7f040019
			public const int notification = 2130968601;
			
			// aapt resource value: 0x7f040022
			public const int permissionBtn = 2130968610;
			
			// aapt resource value: 0x7f040020
			public const int permissionLayout = 2130968608;
			
			// aapt resource value: 0x7f040024
			public const int postBtn = 2130968612;
			
			// aapt resource value: 0x7f040032
			public const int postImage = 2130968626;
			
			// aapt resource value: 0x7f040043
			public const int postImage2 = 2130968643;
			
			// aapt resource value: 0x7f04004c
			public const int postImg = 2130968652;
			
			// aapt resource value: 0x7f04001d
			public const int postingDetailsLayout = 2130968605;
			
			// aapt resource value: 0x7f04002b
			public const int postingScrollableLayout = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int profile = 2130968618;
			
			// aapt resource value: 0x7f04000a
			public const int profilePic1 = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int profilePic2 = 2130968591;
			
			// aapt resource value: 0x7f040014
			public const int profilePic3 = 2130968596;
			
			// aapt resource value: 0x7f040056
			public const int progressEntry = 2130968662;
			
			// aapt resource value: 0x7f040055
			public const int progressEntrySection = 2130968661;
			
			// aapt resource value: 0x7f040006
			public const int seachTxt = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int seacrhBarLayout = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int searchBtn = 2130968583;
			
			// aapt resource value: 0x7f040026
			public const int sharingBtn = 2130968614;
			
			// aapt resource value: 0x7f04001e
			public const int subjectText = 2130968606;
			
			// aapt resource value: 0x7f040021
			public const int textView1 = 2130968609;
			
			// aapt resource value: 0x7f040002
			public const int titleBarLayout = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int titleLabel = 2130968580;
			
			// aapt resource value: 0x7f04004e
			public const int toggleButton1 = 2130968654;
			
			// aapt resource value: 0x7f040031
			public const int top_likedCountTxt = 2130968625;
			
			// aapt resource value: 0x7f040042
			public const int top_likedCountTxt2 = 2130968642;
			
			// aapt resource value: 0x7f04002d
			public const int top_userInfoLayout = 2130968621;
			
			// aapt resource value: 0x7f04003e
			public const int top_userInfoLayout2 = 2130968638;
			
			// aapt resource value: 0x7f04002f
			public const int top_usrInfoTxtLayout = 2130968623;
			
			// aapt resource value: 0x7f040040
			public const int top_usrInfoTxtLayout2 = 2130968640;
			
			// aapt resource value: 0x7f040030
			public const int top_usrNameTxt = 2130968624;
			
			// aapt resource value: 0x7f040041
			public const int top_usrNameTxt2 = 2130968641;
			
			// aapt resource value: 0x7f04002e
			public const int top_usrProfilePic = 2130968622;
			
			// aapt resource value: 0x7f04003f
			public const int top_usrProfilePic2 = 2130968639;
			
			// aapt resource value: 0x7f04000b
			public const int topicBar1 = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int topicBar2 = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int topicBar3 = 2130968597;
			
			// aapt resource value: 0x7f040009
			public const int topicLayout1 = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int topicLayout2 = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int topicLayout3 = 2130968595;
			
			// aapt resource value: 0x7f04000c
			public const int topicSubject1 = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int topicSubject2 = 2130968593;
			
			// aapt resource value: 0x7f040016
			public const int topicSubject3 = 2130968598;
			
			// aapt resource value: 0x7f040037
			public const int usrCommentRowLayout = 2130968631;
			
			// aapt resource value: 0x7f04003a
			public const int usrCommentRowLayout2 = 2130968634;
			
			// aapt resource value: 0x7f040048
			public const int usrCommentRowLayout2_2 = 2130968648;
			
			// aapt resource value: 0x7f040039
			public const int usrCommentTxt = 2130968633;
			
			// aapt resource value: 0x7f04003c
			public const int usrCommentTxt2 = 2130968636;
			
			// aapt resource value: 0x7f04004a
			public const int usrCommentTxt2_2 = 2130968650;
			
			// aapt resource value: 0x7f04002c
			public const int usrPostLayout = 2130968620;
			
			// aapt resource value: 0x7f04003d
			public const int usrPostLayout2 = 2130968637;
			
			// aapt resource value: 0x7f040036
			public const int wholeCommentLayout = 2130968630;
			
			// aapt resource value: 0x7f040047
			public const int wholeCommentLayout2 = 2130968647;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int comm_advice_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int comm_advice_new = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int comm_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int comm_sharing_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int comm_sharing_new = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FirstView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
