#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("healthJourney.droid.Resource", IsApplication=true)]

namespace healthJourney.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::healthJourney.droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::healthJourney.droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::healthJourney.droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::healthJourney.droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::healthJourney.droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::healthJourney.droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::healthJourney.droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::healthJourney.droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::healthJourney.droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::healthJourney.droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::healthJourney.droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::healthJourney.droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::healthJourney.droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::healthJourney.droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::healthJourney.droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::healthJourney.droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::healthJourney.droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::healthJourney.droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::healthJourney.droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bell = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int columns1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int columns4 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int comm_sharing_pic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int comment = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int diet = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int exercise = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int exercise1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int flowers0 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int flowers100 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int flowers25 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int flowers50 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int flowers75 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int lifestyle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int love = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int professional_advice = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int profilePic = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int profilePic2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int profilePic3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int profilePic4 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int share = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sleep = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splashScreen = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sunrise = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050069
			public const int EditAddressView = 2131034217;
			
			// aapt resource value: 0x7f050066
			public const int EditBirthdayView = 2131034214;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050020
			public const int PostDetailTxt = 2131034144;
			
			// aapt resource value: 0x7f050028
			public const int ViewSliderSection = 2131034152;
			
			// aapt resource value: 0x7f050089
			public const int absoluteLayout1 = 2131034249;
			
			// aapt resource value: 0x7f05006a
			public const int address_section1 = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int address_section2 = 2131034219;
			
			// aapt resource value: 0x7f05002a
			public const int adviceBtn = 2131034154;
			
			// aapt resource value: 0x7f050003
			public const int backBtn = 2131034115;
			
			// aapt resource value: 0x7f050065
			public const int birthday_section = 2131034213;
			
			// aapt resource value: 0x7f050015
			public const int bkBtn = 2131034133;
			
			// aapt resource value: 0x7f050027
			public const int btmTabLayout = 2131034151;
			
			// aapt resource value: 0x7f05008a
			public const int btmUsrInfoLayout = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int btm_usrNameTxt = 2131034251;
			
			// aapt resource value: 0x7f05008c
			public const int btm_usrPostTxt = 2131034252;
			
			// aapt resource value: 0x7f050085
			public const int btnLayout1 = 2131034245;
			
			// aapt resource value: 0x7f05000c
			public const int cancelBtn = 2131034124;
			
			// aapt resource value: 0x7f050087
			public const int commentBtn1 = 2131034247;
			
			// aapt resource value: 0x7f050025
			public const int commentTxt = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int commentTxtLayout = 2131034147;
			
			// aapt resource value: 0x7f05008f
			public const int commentUsrIdTxt = 2131034255;
			
			// aapt resource value: 0x7f050092
			public const int commentUsrIdTxt2 = 2131034258;
			
			// aapt resource value: 0x7f050026
			public const int comment_datetimeTxt = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int comment_usrName1 = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int comment_usrPic1 = 2131034146;
			
			// aapt resource value: 0x7f05000b
			public const int community = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int descText = 2131034127;
			
			// aapt resource value: 0x7f050074
			public const int detail_btn_section = 2131034228;
			
			// aapt resource value: 0x7f050041
			public const int diet1 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int diet1SelectBtn = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int diet2 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int diet2SelectBtn = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int diet3 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int diet3SelectBtn = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int diet4 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int diet4SelectBtn = 2131034184;
			
			// aapt resource value: 0x7f05003f
			public const int dietBtn = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int diet_btn_section = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int diet_section = 2131034176;
			
			// aapt resource value: 0x7f050030
			public const int editText = 2131034160;
			
			// aapt resource value: 0x7f050064
			public const int edit_info_section = 2131034212;
			
			// aapt resource value: 0x7f050036
			public const int exercise1 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int exercise1SelectBtn = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int exercise2 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int exercise2SelectBtn = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int exercise3 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int exercise3SelectBtn = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int exercise4 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int exercise4SelectBtn = 2131034173;
			
			// aapt resource value: 0x7f050034
			public const int exerciseBtn = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int exercise_btn_section = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int exercise_section = 2131034165;
			
			// aapt resource value: 0x7f050067
			public const int filler1 = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int filler2 = 2131034216;
			
			// aapt resource value: 0x7f050008
			public const int forumLayout = 2131034120;
			
			// aapt resource value: 0x7f050084
			public const int frameLayout1 = 2131034244;
			
			// aapt resource value: 0x7f05005f
			public const int goalCount = 2131034207;
			
			// aapt resource value: 0x7f05007a
			public const int group_btn_section = 2131034234;
			
			// aapt resource value: 0x7f05001a
			public const int headerTxt1 = 2131034138;
			
			// aapt resource value: 0x7f05002b
			public const int healthJourney = 2131034155;
			
			// aapt resource value: 0x7f050077
			public const int history_btn_section = 2131034231;
			
			// aapt resource value: 0x7f050013
			public const int imageView1 = 2131034131;
			
			// aapt resource value: 0x7f050056
			public const int lifestyle = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int lifestyle1 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int lifestyle1SelectBtn = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int lifestyle2 = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int lifestyle2SelectBtn = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int lifestyle3 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int lifestyle3SelectBtn = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int lifestyle4 = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int lifestyle4SelectBtn = 2131034206;
			
			// aapt resource value: 0x7f050055
			public const int lifestyleBtn = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int lifestyle_btn_section = 2131034196;
			
			// aapt resource value: 0x7f050086
			public const int loveBtn1 = 2131034246;
			
			// aapt resource value: 0x7f05000a
			public const int newPostBtn = 2131034122;
			
			// aapt resource value: 0x7f05002e
			public const int newThoughtsBtn = 2131034158;
			
			// aapt resource value: 0x7f050009
			public const int notification = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int permissionBtn = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int permissionLayout = 2131034128;
			
			// aapt resource value: 0x7f050063
			public const int pictureView = 2131034211;
			
			// aapt resource value: 0x7f05007c
			public const int plan_btn_section = 2131034236;
			
			// aapt resource value: 0x7f050014
			public const int postBtn = 2131034132;
			
			// aapt resource value: 0x7f05002f
			public const int postImg = 2131034159;
			
			// aapt resource value: 0x7f05000d
			public const int postingDetailsLayout = 2131034125;
			
			// aapt resource value: 0x7f05002d
			public const int postingScrollableLayout = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int profile = 2131034156;
			
			// aapt resource value: 0x7f050073
			public const int profileEditBtn = 2131034227;
			
			// aapt resource value: 0x7f050062
			public const int profileImg = 2131034210;
			
			// aapt resource value: 0x7f050017
			public const int profilePic2 = 2131034135;
			
			// aapt resource value: 0x7f050060
			public const int profilePic3 = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int profile_edit_section = 2131034209;
			
			// aapt resource value: 0x7f05006e
			public const int profile_info = 2131034222;
			
			// aapt resource value: 0x7f05006d
			public const int profile_section = 2131034221;
			
			// aapt resource value: 0x7f050032
			public const int progressEntry = 2131034162;
			
			// aapt resource value: 0x7f05006c
			public const int saveBtn = 2131034220;
			
			// aapt resource value: 0x7f050006
			public const int seachTxt = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int seacrhBarLayout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int searchBtn = 2131034119;
			
			// aapt resource value: 0x7f050088
			public const int shareButton1 = 2131034248;
			
			// aapt resource value: 0x7f050029
			public const int sharingBtn = 2131034153;
			
			// aapt resource value: 0x7f05004c
			public const int sleep1 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int sleep1SelectBtn = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int sleep2 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int sleep2SelectBtn = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int sleep3 = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int sleep3SelectBtn = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int sleep4 = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int sleep4SelectBtn = 2131034195;
			
			// aapt resource value: 0x7f05004a
			public const int sleepBtn = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int sleep_btn_section = 2131034185;
			
			// aapt resource value: 0x7f05004b
			public const int sleep_section = 2131034187;
			
			// aapt resource value: 0x7f05000e
			public const int subjectText = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textView1 = 2131034129;
			
			// aapt resource value: 0x7f050070
			public const int textView2 = 2131034224;
			
			// aapt resource value: 0x7f050002
			public const int titleBarLayout = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int titleLabel = 2131034116;
			
			// aapt resource value: 0x7f050031
			public const int toggleButton1 = 2131034161;
			
			// aapt resource value: 0x7f050083
			public const int top_likedCountTxt = 2131034243;
			
			// aapt resource value: 0x7f05007f
			public const int top_userInfoLayout = 2131034239;
			
			// aapt resource value: 0x7f050081
			public const int top_usrInfoTxtLayout = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int top_usrNameTxt = 2131034242;
			
			// aapt resource value: 0x7f050080
			public const int top_usrProfilePic = 2131034240;
			
			// aapt resource value: 0x7f050018
			public const int topicBar1 = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int topicLayout1 = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int topicSubject1 = 2131034137;
			
			// aapt resource value: 0x7f050075
			public const int userDetailsBtn = 2131034229;
			
			// aapt resource value: 0x7f05007b
			public const int userGroupsBtn = 2131034235;
			
			// aapt resource value: 0x7f050078
			public const int userHistoryBtn = 2131034232;
			
			// aapt resource value: 0x7f05001b
			public const int userInformationLayout = 2131034139;
			
			// aapt resource value: 0x7f05007d
			public const int userPlanBtn = 2131034237;
			
			// aapt resource value: 0x7f050076
			public const int user_details = 2131034230;
			
			// aapt resource value: 0x7f050079
			public const int user_history = 2131034233;
			
			// aapt resource value: 0x7f050071
			public const int user_hobbys = 2131034225;
			
			// aapt resource value: 0x7f050072
			public const int user_interests = 2131034226;
			
			// aapt resource value: 0x7f05006f
			public const int user_name = 2131034223;
			
			// aapt resource value: 0x7f050021
			public const int usrCommentBox1 = 2131034145;
			
			// aapt resource value: 0x7f05008e
			public const int usrCommentRowLayout = 2131034254;
			
			// aapt resource value: 0x7f050091
			public const int usrCommentRowLayout2 = 2131034257;
			
			// aapt resource value: 0x7f050090
			public const int usrCommentTxt = 2131034256;
			
			// aapt resource value: 0x7f050093
			public const int usrCommentTxt2 = 2131034259;
			
			// aapt resource value: 0x7f05001f
			public const int usrDetails = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int usrName = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int usrPic2 = 2131034140;
			
			// aapt resource value: 0x7f05007e
			public const int usrPostLayout = 2131034238;
			
			// aapt resource value: 0x7f05001d
			public const int ustInfoTxtLayout = 2131034141;
			
			// aapt resource value: 0x7f05008d
			public const int wholeCommentLayout = 2131034253;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int comm_advice_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int comm_advice_new = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int comm_advice_topic = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int comm_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int comm_sharing_main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int comm_sharing_new = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FirstView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int healthPlanConfig = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int overview_progress = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int postTopicLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int profile_edit = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int profile_main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int progress_entry = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int thoughtlayout = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
